apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_name: bXlkYg==  # base64 encoded value of "mydb"
  db_user: cG9zdGdyZXM=  # base64 encoded value of "postgres"
  db_pass: cGFzc3dvcmQ=  # base64 encoded value of "password"
