apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  postgres_db: bXlkYg== # Base64-encoded value for "mydb"
  postgres_user: cG9zdGdyZXM= # Base64-encoded value for "postgres"
  postgres_password: cGFzc3dvcmQ= # Base64-encoded value for "password"
